### ISSUE TITLE
List rules with better tips when resources not found

### ISSUE THREAD

**Issue by songjiayang** [cortexproject/cortex-tools#11]
Currently `cortextool rules list` cmd will pinic an error when no rule groups found, see code [rules.go#L332](https://github.com/cortexproject/cortex-tools/blob/main/pkg/commands/rules.go#L332). 

Can we change it like rules print, add ErrResourceNotFound check?

```
if err == client.ErrResourceNotFound {
	log.Infof("no rule groups currently exist for this user")
	return nil
}
```

**Comment by CharlieTLe** [comment]
This should be fixed in #29
